CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
email varchar(320) NOT NULL,
name varchar(100) NOT NULL,
CONSTRAINT pk_user PRIMARY KEY (id),
CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
owner BIGINT NOT NULL,
name VARCHAR(250) NOT NULL,
description VARCHAR(1000) NOT NULL,
available bool DEFAULT 'false',
request BIGINT,
CONSTRAINT pk_item PRIMARY KEY (id),
CONSTRAINT fk_items_to_users FOREIGN KEY(owner) REFERENCES users(id)
);

--CREATE TABLE IF NOT EXISTS tags (
--id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--item_id BIGINT, name VARCHAR(50),
--CONSTRAINT fk_tags_to_items FOREIGN KEY(item_id) REFERENCES items(id)
--);